name: portfolio
description: My Portfolio website
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0

dev_dependencies:
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
